fixtures:
  repositories:
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    apt:
      repo: 'https://github.com/puppetlabs/puppetlabs-apt.git'
      branch: '1.8.x'
    zypprepo: https://github.com/deadpoint/puppet-zypprepo.git
  symlinks:
    elasticsearch: "#{source_dir}"
